/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://4flcuyexire6xdyhh7ptk2efza.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kccbxv3x7nhhlkddxa3l6zkhnq",
    "aws_cognito_identity_pool_id": "us-east-1:62dafa55-f8d7-4947-aae2-2c7b02ef4b8b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_PmPRQqkPG",
    "aws_user_pools_web_client_id": "157vbnf2dkub4mpg355q8nde9v",
    "oauth": {}
};


export default awsmobile;
