/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createRecord = /* GraphQL */ `
  mutation CreateRecord($input: InputSmartdash!) {
    createRecord(input: $input) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      adquisition
      account
      notes
      smName
      smAddress
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_discount
      l_team
      l_leadsStatus
      l_quoteLibrary
      l_quoteStatus
      l_variant
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      disccountAmount
      l_disccount
      quotationAmount
      finalAmount
      paymentStatus
      orderNumber
      processStatus
      description
      price
      typeName
      otherType
      isRecurrent
      isVariant
      variants
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskNameResponsible
      startDate
      amount
      isPaid
      reference
      method
      payDate
      value
      type
      live
      revisitDate
      customerID
      customerName
      businessType
      l_businessType
      jobTitle
      levelAuthority
      numberEmployee
      scale
    }
  }
`;
export const updateRecord = /* GraphQL */ `
  mutation UpdateRecord($input: InputSmartdash!) {
    updateRecord(input: $input) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      adquisition
      account
      notes
      smName
      smAddress
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_discount
      l_team
      l_leadsStatus
      l_quoteLibrary
      l_quoteStatus
      l_variant
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      disccountAmount
      l_disccount
      quotationAmount
      finalAmount
      paymentStatus
      orderNumber
      processStatus
      description
      price
      typeName
      otherType
      isRecurrent
      isVariant
      variants
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskNameResponsible
      startDate
      amount
      isPaid
      reference
      method
      payDate
      value
      type
      live
      revisitDate
      customerID
      customerName
      businessType
      l_businessType
      jobTitle
      levelAuthority
      numberEmployee
      scale
    }
  }
`;
export const deletePhoneNumber = /* GraphQL */ `
  mutation DeletePhoneNumber($input: DeleteInput!) {
    deletePhoneNumber(input: $input) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      value
      type
    }
  }
`;
export const deleteInstallments = /* GraphQL */ `
  mutation DeleteInstallments($input: DeleteInput!) {
    deleteInstallments(input: $input) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      startDate
      amount
      type
      isPaid
      reference
      method
      payDate
      scale
    }
  }
`;
