/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const createRecord = /* GraphQL */ `
  mutation CreateRecord($input: InputSmartdash!) {
    createRecord(input: $input) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const updateRecord = /* GraphQL */ `
  mutation UpdateRecord($input: InputSmartdash!) {
    updateRecord(input: $input) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const deletePhoneNumber = /* GraphQL */ `
  mutation DeletePhoneNumber($input: DeleteInput!) {
    deletePhoneNumber(input: $input) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      value
      type
      l_emails
      customerName
    }
  }
`;
export const deleteInstallments = /* GraphQL */ `
  mutation DeleteInstallments($input: DeleteInput!) {
    deleteInstallments(input: $input) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      startDate
      amount
      type
      isPaid
      reference
      method
      customerName
      payDate
      scale
    }
  }
`;
