/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const listOrganizations = /* GraphQL */ `
  query ListOrganizations(
    $filter: TableFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listOrganizations(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_discount
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const getOrganization = /* GraphQL */ `
  query GetOrganization($filter: TableFilterInput) {
    getOrganization(filter: $filter) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_discount
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const listCustomers = /* GraphQL */ `
  query ListCustomers(
    $filter: TableFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listCustomers(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
    }
  }
`;
export const getCustomer = /* GraphQL */ `
  query GetCustomer($PK: String!, $SK: String!) {
    getCustomer(PK: $PK, SK: $SK) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
    }
  }
`;
export const listProducts = /* GraphQL */ `
  query ListProducts(
    $filter: TableFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listProducts(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const getProduct = /* GraphQL */ `
  query GetProduct($filter: TableFilterInput) {
    getProduct(filter: $filter) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      description
      price
      productType
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
    }
  }
`;
export const listQuotes = /* GraphQL */ `
  query ListQuotes($filter: TableFilterInput, $limit: Int, $nextToken: String) {
    listQuotes(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const listInvoices = /* GraphQL */ `
  query ListInvoices(
    $filter: TableFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listInvoices(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const getQuote = /* GraphQL */ `
  query GetQuote($PK: String!, $SK: String!) {
    getQuote(PK: $PK, SK: $SK) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const listQuoteItems = /* GraphQL */ `
  query ListQuoteItems(
    $filter: TableFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listQuoteItems(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const getQuoteItem = /* GraphQL */ `
  query GetQuoteItem($filter: TableFilterInput) {
    getQuoteItem(filter: $filter) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      description
      price
      productType
      otherType
      isRecurrent
      isVariant
      variantName
      variantPrice
      internalComments
      customerName
      estimatedHours
      publicLink
      internalLink
    }
  }
`;
export const listInstallments = /* GraphQL */ `
  query ListInstallments(
    $filter: TableFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listInstallments(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const getInstallment = /* GraphQL */ `
  query GetInstallment($PK: String!, $SK: String!) {
    getInstallment(PK: $PK, SK: $SK) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      startDate
      amount
      type
      isPaid
      reference
      method
      customerName
      payDate
      scale
    }
  }
`;
export const listEmployee = /* GraphQL */ `
  query ListEmployee(
    $filter: TableFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listEmployee(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      l_smName
      email
    }
  }
`;
export const getEmployee = /* GraphQL */ `
  query GetEmployee($PK: String!, $SK: String!) {
    getEmployee(PK: $PK, SK: $SK) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      l_smName
      email
    }
  }
`;
export const listLogs = /* GraphQL */ `
  query ListLogs($filter: TableFilterInput, $limit: Int, $nextToken: String) {
    listLogs(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      table
      type
      idRegistry
      l_value
    }
  }
`;
export const getLogs = /* GraphQL */ `
  query GetLogs($PK: String!, $SK: String!) {
    getLogs(PK: $PK, SK: $SK) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      table
      type
      idRegistry
      l_value
    }
  }
`;
export const listPhoneNumber = /* GraphQL */ `
  query ListPhoneNumber(
    $filter: TableFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listPhoneNumber(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      value
      type
      l_email
      customerName
    }
  }
`;
export const getPhoneNumber = /* GraphQL */ `
  query GetPhoneNumber($limit: Int, $nextToken: String) {
    getPhoneNumber(limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      value
      type
      l_email
      customerName
    }
  }
`;
export const listSmartDash = /* GraphQL */ `
  query ListSmartDash(
    $filter: TableFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listSmartDash(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const listAccounts = /* GraphQL */ `
  query ListAccounts($filter: TableFilterInput) {
    listAccounts(filter: $filter) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
    }
  }
`;
export const getAccounts = /* GraphQL */ `
  query GetAccounts($flter: TableFilterInput) {
    getAccounts(flter: $flter) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
    }
  }
`;
export const listCampaings = /* GraphQL */ `
  query ListCampaings(
    $filter: TableFilterInput
    $limit: Int
    $nextToken: String
  ) {
    listCampaings(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
export const listTask = /* GraphQL */ `
  query ListTask($filter: TableFilterInput, $limit: Int, $nextToken: String) {
    listTask(filter: $filter, limit: $limit, nextToken: $nextToken) {
      GSP1PK1
      GSP1SK1
      GSP2PK1
      GSP2SK1
      GSP3PK1
      GSP3SK1
      GSP4PK1
      GSP4SK1
      PK
      SK
      id
      entityType
      createdAt
      updateAt
      active
      createdBy
      smName
      smAddress
      website
      productType
      amount
      date
      l_smName
      l_email
      l_smAddress
      leadStatus
      seekingService
      acquisition
      account
      notes
      businessType
      jobTitle
      levelAuthority
      numberEmployee
      email
      table
      type
      idRegistry
      l_value
      value
      customerName
      description
      price
      otherType
      isRecurrent
      isVariant
      l_variant
      estimatedHours
      publicLink
      internalLink
      subject
      introduction
      conclusion
      internalComments
      emailSent
      sentDate
      sentBy
      isDiscount
      isInstallment
      downPayment
      numInstallments
      discountAmount
      l_discount
      l_installments
      quotationAmount
      finalAmount
      processStatus
      purchased
      live
      revisitDate
      payDate
      paidAmount
      balance
      annulled
      quoteID
      variantName
      variantPrice
      taskStatus
      taskStart
      taskEnd
      taskResponsible
      startDate
      isPaid
      reference
      method
      scale
      l_productType
      l_acquisition
      l_taskStatusType
      l_paymentMethod
      l_team
      l_leadStatus
      l_quoteLibrary
      l_quoteStatus
      l_businessType
      funcRegion
      funcIdentityPoolId
      funcName
      funcSource
    }
  }
`;
